### PR TITLE
Switch from distutils LooseVersion to Version

### PR DESCRIPTION
**Pull request by maresb**
Fix DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Checklist
* [X] Added a ``news`` entry

### CODE REVIEW

**Comment by maresb** [comment]
Warning: I haven't run the tests locally, and I'm not sure if there are differences between `distutils.version.LooseVersion` and `packaging.Version`.

**Review by jfrost-mo — APPROVED** [review]
Looks fine to me. Version has slightly different semantics to LooseVersion, but really only around handling of very weird version numbers. This shouldn't be an issue, as conda and mamba both use sane versions.

I've lightly tested, and it appears to work with the changes, including in python 3.12.

**Comment by jfrost-mo** [comment]
@mariusvniekerk sorry for the ping, but would it be possible to get this reviewed and merged? Its currently causing ensureconda to fail on Python 3.12.

**Comment by maresb** [comment]
Ping @mariusvniekerk

**Comment by SINC-G** [comment]
Sorry for ping again, it's stuck too long.

**Pull request merged**
